language: cpp
dist: bionic
sudo: required
osx_image: xcode12.2

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TEST_INSTALL=0 RUN_TEST=1 THREADING="none" BUILD_CONFIG="auto"
  - TEST_INSTALL=0 RUN_TEST=1 THREADING="none" BUILD_CONFIG="reference"
  - TEST_INSTALL=1 RUN_TEST=0 THREADING="none" BUILD_CONFIG="auto"
  - TEST_INSTALL=0 RUN_TEST=0 THREADING="openmp" BUILD_CONFIG="auto"
  - TEST_INSTALL=0 RUN_TEST=0 THREADING="pthreads" BUILD_CONFIG="auto"
  - TEST_INSTALL=0 RUN_TEST=0 THREADING="tbb" BUILD_CONFIG="auto"

matrix:
  exclude:
    - env: TEST_INSTALL=0 RUN_TEST=1 THREADING="none" BUILD_CONFIG="auto"
      os: osx
    - env: TEST_INSTALL=0 RUN_TEST=1 THREADING="none" BUILD_CONFIG="reference"
      os: osx
    - env: TEST_INSTALL=1 RUN_TEST=0 THREADING="none" BUILD_CONFIG="auto"
      os: osx
    - env: TEST_INSTALL=0 RUN_TEST=0 THREADING="tbb" BUILD_CONFIG="auto"
      os: osx
  
before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        rm /usr/local/include/c++;
        brew update && brew install gcc@9 tbb llvm@9;
        rm /usr/local/include/c++;
        brew link --force --overwrite llvm@9;
    fi'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-6
    packages:
    - gcc-9
    - g++-9
    - clang-6.0
    - libiomp-dev
    - libtbb-dev
    #- binutils-2.26
    
install:
  #- 'if [ "$TRAVIS_OS_NAME" = "linux" ]; then
  #      export PATH=/usr/lib/binutils-2.26/bin:${PATH};
  #  fi'
  - if [ "$CC" = "gcc" ] ; then export CC="gcc-9" CXX="g++-9"; fi
  - 'if [ "$CC" = "clang" ] ; then
        if [ "$TRAVIS_OS_NAME" = "linux" ]; then
            export CC="clang-6.0 -fopenmp=libiomp5" CXX="clang++-6.0 -fopenmp=libiomp5";
        else
            export CC="clang-9" CXX="clang++";
        fi;
    fi'

script:
  - $CC --version
  - $CXX --version
  - as --version
  - ./configure CC="$CC" CXX="$CXX" --enable-threading="$THREADING" --enable-config="$BUILD_CONFIG" --prefix=`pwd`/install
  - cat config.log src/external/tci/config.log
  - make -j 2
  - if [ $RUN_TEST -eq 1 ]; then travis_wait 30 bin/test; fi
  - 'if [ $TEST_INSTALL -eq 1 ]; then
        make install;
        $CXX -std=c++14 -o test_install -I./install/include test/test_install.cxx -L./install/lib -ltblis;
    fi'
