name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make file
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: cmake --build build -j$(nproc)
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
      - name: Configure (Autotools)
        run: |
          mkdir autobuild
          cd autobuild
          ../configure
      - name: Make
        run: |
          cd autobuild
          make -j$(nproc)
      - name: Make check
        run: |
          cd autobuild
          make check

